message(STATUS "Setting up Warp SDK (CMake)")

if(NOT STATEDIR)
    message(FATAL_ERROR "STATEDIR required.")
endif()

set(setup "${STATEDIR}/warpsdk-setup")
file(MAKE_DIRECTORY "${setup}")

set(deps
    warp-sysroot
    warpsdk-cmake-tc)

set(envvars
    WARPSDK_CMAKE_MODULES
    WARPSDK_SYSROOT
    WARP_TOOLCHAIN_PREFIX)

set(requires)
foreach(d IN LISTS deps)
    list(APPEND requires --requires=${d}/[>=0])
endforeach()

execute_process(COMMAND
    conan install --build=missing
    ${requires}
    --tool-requires=warpsdk-llvm/[>=0]
    WORKING_DIRECTORY "${setup}"
    RESULT_VARIABLE rr)

# Extract envvars
if(WIN32)
    message(FATAL_ERROR "Unimpl.")
    # NB: Convert these to CMake paths
else()
    foreach(v IN LISTS envvars)
        execute_process(COMMAND
            sh -c "source ${setup}/conanbuild.sh && echo xxxx${v}: \$${v}"
            OUTPUT_VARIABLE out
        )
        if("${out}" MATCHES "xxxx${v}: (.*)")
            set(value "${CMAKE_MATCH_1}")
            string(STRIP "${value}" value)
            message(STATUS "${v}: ${value}")
            set(${v} ${value})
        else()
            message(FATAL_ERROR "Could not fetch envvar ${v}")
        endif()
    endforeach()
endif()

# Output envvars
set(outfile "${STATEDIR}/warpsdk-vars.cmake")
file(WRITE "${outfile}" "# Autogenerated, do not edit\n\n")
foreach(v IN LISTS envvars)
    file(APPEND "${outfile}" "set(${v} \"${${v}}\")\n")
endforeach()
